services:
  postgres:
    image: docker.io/library/postgres:16 
    container_name: reksadana_pg
    environment:
      POSTGRES_DB: reksadana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Data Storing/src/ddl_oltp.sql:/docker-entrypoint-initdb.d/01_oltp.sql:ro,Z
      - ./Data Storing/Data Warehouse/src/ddl_dw.sql:/docker-entrypoint-initdb.d/02_dw.sql:ro,Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reksadana"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: reksadana_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reksadana.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
